classdef const
    %CONST Constants for the LMB toolbox.

    properties(Constant)
        OCPROOT = TB.getAbsPath('OCP');
        NLEISROOT = TB.getAbsPath('NLEIS');
        RPTROOT = TB.getAbsPath('RPT');
        GITTROOT = TB.getAbsPath('GITT');
        ROMROOT = TB.getAbsPath('ROM');
        DEMOROOT = TB.getAbsPath('DEMO');
        VERSION = '2.0.0';
        AUTHOR = 'Wesley Hileman <whileman@uccs.edu>';

        % Physical constants.
        R = 8.3144598;      % Molar gas constant [J/mol K]
        F = 96485.3329;     % Faraday constant [C/mol]

        % Parameter descriptions/latex/units.
        LUMPED_PARAMETER_METADATA = struct( ...
            'U0',       struct('d','MSMR equilibrium voltages','l','\{U_j^0\}','u','V'), ...
            'X',        struct('d','MSMR gallery sizes','l','\{X_j\}','u','unitless'), ...
            'omega',    struct('d','MSMR reaction type tuning value','l','\{\omega_j\}','u','unitless'), ...
            'theta0',   struct('d','Electrode Stoichiometry at 0% SOC','l','\theta_{0}','u','unitless'), ...
            'theta100', struct('d','Electrode Stoichiometry at 100% SOC','l','\theta_{100}','u','unitless'), ...
            'sigma',    struct('d','Lumped Solid Phase Conductivity','l','\bar{\sigma}','u','1/Ohm'), ...
            'kappa',    struct('d','Lumped Electrolyte Phase Conductivity','l','\bar{\kappa}','u','1/Ohm'), ...
            'Dsref',    struct('d','Lumped Solid Phase Diffusivity','l','\bar{D}_{\mathrm{s,ref}}','u','1/s'), ...
            'nF',       struct('d','Solid-phase diffusivity CPE factor','l','n_\mathrm{f}','u','unitless'), ...
            'tauW',     struct('d','Warburg time constant','l','\bar{\tau}_\mathrm{W}','u','s'), ...
            'k0',       struct('d','Lumped reaction rate coefficient','l','\{\bar{k}_{0,j}\}','u','A'), ...
            'alpha',    struct('d','Lumped alpha','l','\{\alpha_j\}','u','unitless'), ...
            'Rf',       struct('d','Lumped SEI film resistance','l','\bar{R}_\mathrm{f}','u','Ohm'), ...
            'Cdl',      struct('d','Double-layer capacitance','l','\bar{C}_\mathrm{dl}','u','F'), ...
            'nDL',      struct('d','Double-layer CPE factor','l','n_\mathrm{dl}','u','unitless'), ...
            'wDL',      struct('d','Double-layer CPE frequency breakpoint','l','w_\mathrm{dl}','u','rad/s'), ...
            'Rdl',      struct('d','Double-layer resistance','l','\bar{R}_\mathrm{dl}','u','Ohm'), ...
            'W',        struct('d','Warburg resistance factor of electrolyte','l','\bar{W}','u','unitless'), ...
            'Q',        struct('d','Cell total capacity','l','Q','u','A*h'), ...
            'psi',      struct('d','Estimate of F*c0*kappa/De/T/(1-t0p) ','l','\bar{\psi}','u','V/K'), ...
            'Tref',     struct('d','Reference temperature','l','T_\mathrm{ref}','u','K') ...
        ); % LUMPED_PARAMETER_METADATA
    end

    methods(Static)
        function f = f(TdegC)
            %F Compute f=F/(R*T) for the supplied T in [C].
            if ~exist('T','var')
                TdegC = 25;
            end
            f = TB.const.F/TB.const.R/(TdegC+273.15);
        end
    end

end